config/routes.rb
Rails.application.routes.draw do

  get 'main/restricted'

  root 'main#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get '/' => 'main#index'
  get 'newpost' => 'main#newpost'
  post 'newpost' => 'main#createpost'

  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comment

end

app/models/user.rb
class User < ActiveRecord::Base

	validates :email,
	presence: true,
	#have emails that are unique, pass as a hash
	uniqueness: {case_sensitive: false},
  email: true

  has_many :post
  has_many :comment

  # validated :password,
  # presence: true

  #shortened version:
  validates_presence_of :password, on: :create
  #chain diff. validators after that

	has_secure_password

  def self.authenticate email, password
    #pass email parameter to return a user
    User.find_by_email(email).try(:authenticate, password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :current_user

	def is_authenticated?
		unless current_user
			flash[:danger] = 'invalid'
			redirect_to login_path
		end
	end

	def current_user
		@current_user ||= User.find_by_id(session[:user_id])
	end
end

app/controllers/comments_controller.rb
# class CommentsController < ApplicationController
# 	before_action :is_authenticated?
# 	# belongs_to :user
# 	# has_many :comments

# 	def index
# 	@comments = Comment.all
# 	end

# 	def newcomment
# 	# @tags = Tag.all
# 	@comment = Comment.new

# 	end


# 	def create

# 		comment = Post.find_by_id(params[:post_id]).comment.create comment_params
# 		current_user.comment << comment
# 		# puts Post.find_by_id([3])
# 		redirect_to root_path
# 	end

# 	def destroy
#     c = Comment.find params[:id]
#     c.delete
#     redirect_to post_comments_path(params[:post_id])
#   	end

# 	private

# 	def comment_params
# 		params.require(:comment).permit(:body)
# 	end

# end

class CommentsController < ApplicationController
  before_action :is_authenticated?, except: [:index]

  def index
    @post = Post.find params[:post_id]
  end

  def new
    @post = Post.find params[:post_id]
    @comment = Comment.new
  end

  def create
    Comment.create comment_params do |c|
      c.post_id = params[:post_id]
      c.user_id = @current_user.id
      c.save
    end
    redirect_to post_comments_path(params[:post_id])
  end

  def destroy
    c = Comment.find params[:id]
    c.delete
    redirect_to post_comments_path(params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	before_action :is_authenticated?
	#question mark is used in ruby to return a boolean value

  def index
  	# current_user
  	@posts = Post.all
  end

	def newpost
	# @tags = Tag.all
	@post = Post.new

	end

	def createpost
		User.find_by_id(session[:user_id]).post.create createpost_params
		redirect_to root_path
	end

	private

	def createpost_params
		params.require(:user).permit(:title, :link)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


before_action :is_authenticated?

	def index
		# current_user
	end

	def newpost
		# @post = Post.new
	end

	def createpost
		User.find_by_id(session[:user_id]).post.create createpost_params
		redirect_to root_path
	end

	private

	def createpost_params
		params.require(:user).permit(:title, :link)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

#render login form
	def new
	end

#login form data, parameters, create a new session
	def create
		#pass in login params
		#returns the user if correctly authenticated
		#store as a variable (user=)
	user = User.authenticate login_params['email'], login_params['password']
		#set truthy or falsey
	if user
			#grab id and store in session
		session[:user_id] = user.id
		flash[:success] = "#{user.email} has logged in successfully"
		redirect_to login_path

		else
			#give an error
		flash[:danger] = "Incorrect email and/or password"
		redirect_to login_path
	end
end

	#public method
	def destroy
		session[:user_id] = nil
		redirect_to login_path
	end


	private

	#filter out parameters, inject data into model
	def login_params
		params.require(:user).permit(:email, :password)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new # render the signup form
        
    end

    def create # creates a new user in db
        User.create signup_params
        redirect_to root_path
    end

    def show
        @post = Posts.all
    end

    private

    def signup_params
          params.require(:user).permit(:email, :password, :name)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<div class="page-header">

<h1><%= link_to @p.title, @p.link %></h1>
<%= link_to 'New Comment', new_post_comment_path(post), class: 'btn pull-right' %>
</div>
		
	<%= form_for :comment do |f| %>
  		<%= f.text_area :body, placeholder: 'Comment' %>
  		<% f.hidden_field :user_id%>

  		<%= f.submit 'Post' %>



<%= link_to @post.title, @post.link %>
<%= link_to 'New Comment', new_post_comment_path(@post), class: 'btn pull-right' %>

<% @post.comment.each do |comment| %>
	  	<p><%= comment.body %></p>
	  	<%= link_to '', post_comment_path(@post, comment), class: 'fa fa-times', method: :delete %>


</div>
<% end %>
		<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snaplinks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.0/css/materialize.min.css">
<link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

</head>
<body>


<%= render 'partials/flash' %>


  <nav>
    <div class="nav-wrapper teal lighten-3">
      <a href="#" class="brand-logo"></a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li><h2><a href="/login">Login</a><h2></li>
        <li><h2><a href="/signup">Signup</a></h2></li>
      </ul>
    </div>
  </nav>
        

			<%= yield %>



<script src="//code.jquery.com/jquery.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.0/js/materialize.min.js"></script>
</body>
</html>

app/views/main/index.html.erb
<div class="page-header">
	<h1>Snaplinks</h1><br>
		<img src="https://d30y9cdsu7xlg0.cloudfront.net/png/49083-200.png" height="150px"><p>
		<center>
			<h4><%= link_to "New Post", {
			:controller => "main",
			:action => "newpost"
			}%></h4>
		</center>

	</div>

<div class="container">
	<% Post.all.each do |p| %>
	<div class="row" style="align-left">
			<%= link_to p.title, p.link %>

	</div>
</div>

<% end %>

app/views/main/newpost.html.erb
<div class="page-header">
	<h1>Create a post</h1>
</div>

	<div class="container">
		
		<%= form_for :user do |f| %>
  		<%= f.text_field :title, placeholder: 'Title' %>
  		<%= f.text_field :link, placeholder: 'Link' %>

  		<%= f.submit 'Post' %>
	</div>
	
<% end %>

app/views/main/post.html.erb
<h1>Create a post</h1>
		
	<%= bootstrap_form_for :user do |f| %>
  		<%= f.text_field :title %>
  		<%= f.text_area :post %>

  		<%= f.primary %>
		<% end %>

app/views/partials/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>">
    <%= message %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="container">
	<div class="row">
  		<div class="col-xs-8">
    		<h1>Posts</h1>
  		</div>
  		<div class="col-xs-4">
    		<%= link_to '', new_post_path, class: '' %>
  		</div>
	</div>

	<div class='row'>
		<% Post.all.each do |p| %>

			<div class="col-sm-8 col-sm-offset-2">

	  			<h2><%= link_to p.title, p.link %></h2><br>
	  			Posted by <%=p.user.email $>
	  			<%= link_to "delete", {:controller => "posts", :action => "destroy", :id => post.id}

	  	
			</div>
	</div>

</div>

	<% end %>

app/views/posts/new.html.erb
<h1>Create a post</h1>
		
	<%= form_for :user do |f| %>
  		<%= f.text_field :title, placeholder: 'Title' %>
  		<%= f.text_field :link, placeholder: 'Link' %>

  		<%= f.submit 'Post' %>
		<% end %>

app/views/users/new.html.erb
<span align="center"><h1>Signup here</h1></span>
<div class="container" width:"500px">

<%= form_for :user do |f| %>
	<%= f.text_field :name, placeholder:'Name' %>
  <%= f.text_field :email, placeholder:'Email' %>
  <%= f.password_field :password, placeholder: 'Password' %>

  <%= f.submit 'Signup' %>

  </div>
<!--   //instead of f.primary (bootstrap)  -->

<% end %>

app/views/users/profile.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2">
			<h1><%= @current_user.name %>
			<br>Links</h1>
		</div>
	</div>
</div>
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2">
	<% @current_user.post.each do |post| %>
		<ul>
		<li>
		<%= link_to post.title, post.link %>
		</li>
		</ul>
	<% end %>	

</div>
	</div>